spring:

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: akash

  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  h2:
    console:
      enabled: false

  server:
    address: 192.168.0.5
    port: 8080