spring:
  profiles: local-dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: akash

  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  hibernate:
    ddl-auto: update

server:
  port: 9080
