spring:
  application.jwt:
    accessSecretKey: "Secure@MSI@Secure@MSI@Secure@MSI@Secure@MSI@Secure@MSI@Secure@MSI@Secure@MSI@"
    accessTokenPrefix: "Bearer "
    accessTokenExpirationInHours: 1

    refreshSecretKey: "Secure@AntecSecure@AntecSecure@AntecSecure@AntecSecure@AntecSecure@AntecSecure@Antec"
    refreshTokenPrefix: "Refresher "
    refreshTokenExpirationInDays: 2

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: akash

  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  h2:
    console:
      enabled: false

  server:
    address: 192.168.0.5
    port: 8080